# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: aws ec2 deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: deploy pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Repo checkout
      uses: actions/checkout@v3 
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v2.2.11
      with:
        SSH_PRIVATE_KEY: ${{ secrets.R_PKI }}
        REMOTE_HOST: ${{ secrets.R_HOST }}
        REMOTE_USER: ${{ secrets.R_USER }}
        REMOTE_PORT: ${{ secrets.R_PORT }}
        TARGET: /var/www/
     
      
